# -----------------------------------------------------------------------------
# References: https://kerkour.com/rust-small-docker-image
# -----------------------------------------------------------------------------
# Builder: docker build -t wasta:scratch -f Dockerfile.scratch .
# -----------------------------------------------------------------------------
FROM rust:1.66-slim AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

# Create application user
RUN adduser --disabled-password --gecos "" --home "/nonexistent" \
  --shell "/sbin/nologin" --no-create-home --uid 1001 groot

WORKDIR /app
COPY . .

# Use flag `x86_64-unknown-linux-musl` for building for Alpine or Scratch image
RUN cargo build --target x86_64-unknown-linux-musl --release

# -----------------------------------------------------------------------------
# Final image: docker run -it --rm -p 3030:3030 wasta:scratch
# -----------------------------------------------------------------------------
LABEL org.opencontainers.image.source="https://github.com/riipandi/wasta"
FROM scratch

WORKDIR /

# Import user from builder.
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/wasta .

# Use an unprivileged user.
USER groot:groot

CMD ["/wasta"]
