[env]
APP_VERSION = "${CARGO_MAKE_CRATE_VERSION}"
GIT_HASH_SHORT = { script = ["git rev-parse --short HEAD"] }
PKG_WEB_VERSION = { script = ["cat package.json | jq -r .version"] }
IMAGE_NAME = "ghcr.io/riipandi/fastrue"
CONTAINER_NAME = "${CARGO_MAKE_CRATE_NAME}"
BUILD_VERSION = "v${APP_VERSION}-${GIT_HASH_SHORT}"
BIND_PORT = 9090

[tasks.sync-version]
script = ['sed -i "" "s/\"version\": \"$PKG_WEB_VERSION\"/\"version\": \"$APP_VERSION\"/" package.json']

[tasks.sync-types]
command = "tsync"
args = ["-i", "src/", "-o", "websrc/types/types.d.ts"]

[tasks.output-release]
command = "ls"
args = ["-lh", "target/release"]

[tasks.deps-npm]
command = "pnpm"
args = ["install"]

[tasks.deps-rust]
command = "cargo"
args = ["update"]

[tasks.deps]
run_task = { name = ["deps-npm", "deps-rust"] }

[tasks.format-rs]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.format-ts]
command = "pnpm"
args = ["format"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

# --------------------------------------------------------------------------------------------------
# Task for build and compile
# --------------------------------------------------------------------------------------------------

[tasks.build-api]
command = "cargo"
args = ["build", "--release", "--locked"]
dependencies = ["clean"]

[tasks.build-web]
command = "pnpm"
args = ["build"]
dependencies = ["sync-version", "deps-npm", "sync-types", "format-ts"]

[tasks.build]
dependencies = ["format-rs", "build-web", "build-api", "output-release"]

[tasks.run]
command = "cargo"
args = ["run", "--release"]
dependencies = ["format-rs", "build-web"]

# --------------------------------------------------------------------------------------------------
# Task for development
# --------------------------------------------------------------------------------------------------

[tasks.dev-api]
command = "cargo"
args = ["watch", "-qcx", "run"]

[tasks.dev-web]
command = "pnpm"
args = ["dev"]
dependencies = ["sync-types", "format-ts"]

[tasks.dev]
command = "pnpm"
args = ["concurrently", "--kill-others", "'cargo watch -qcx run'", "'pnpm dev'"]

[tasks.generate-secret]
command = "cargo"
args = ["run", "--", "generate-secret"]

[tasks.migrate]
command = "cargo"
args = ["run", "--", "migrate"]

[tasks.create-admin]
command = "cargo"
args = ["run", "--", "create-admin"]

[tasks.run-docs]
command = "zola"
args = ["serve"]
cwd = "./docs/"

# --------------------------------------------------------------------------------------------------
# Task for build and push Docker image
# --------------------------------------------------------------------------------------------------

[tasks.docker-build]
dependencies = ["sync-version", "sync-types", "format-rs", "format-ts"]
command = "docker"
args = [
  "build",
  "-f", "Dockerfile",
  "--build-arg", "BIND_PORT=${BIND_PORT}",
  "-t", "${IMAGE_NAME}:${BUILD_VERSION}",
  "-t", "${IMAGE_NAME}:edge",
  "."
]

[tasks.docker-push]
command = "docker"
args = ["push", "-t", "${IMAGE_NAME}:${BUILD_VERSION}", "-t", "${IMAGE_NAME}:edge"]

[tasks.docker-run]
command = "docker"
args = [
  "run", "--rm", "-it",
  "--name", "${CONTAINER_NAME}",
  "--env-file", ".env.docker",
  "-p", "${BIND_PORT}:${BIND_PORT}",
  "${IMAGE_NAME}:edge"
]

[tasks.deploy-demo]
command = "fly"
args = ["-c", "fly-source.toml", "deploy", "--remote-only"]
