name: docker-action
description: Build and publish docker image

inputs:
  registry-host:
    description: Container registry
    default: docker.io
    required: false
  registry-username:
    description: Registry username
    required: true
  registry-password:
    description: Registry password
    required: true
  image-name:
    description: Container image name
    required: true
  image-tags:
    description: Container image tags
    required: true
  image-platform:
    description: Container image platform
    default: linux/amd64
    required: false

runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry-host }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ inputs.image-name }}
        tags: ${{ inputs.image-tags }}

    - name: Build and push with tags
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: ${{ inputs.image-platform }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
