name: rust-action
description: Setup Rust Toolchain

inputs:
  target-toolchain:
    description: Target toolchain
    default: x86_64-unknown-linux-gnu
    required: false

runs:
  using: composite
  steps:
    - name: Get MSRV from Cargo.toml
      id: msrv
      shell: bash
      run: grep rust-version Cargo.toml | cut -d'"' -f2 | sed 's/^/version=/' >> $GITHUB_OUTPUT
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ steps.msrv.outputs.version }}
        targets: ${{ inputs.target-toolchain }}
        components: rustfmt, clippy

    # - name: Cargo libraries check
    #   shell: bash
    #   run: |
    #     cargo install cargo-make toml-cli --locked
    #     cargo check --all --bins --examples --tests

    - name: Install Windows libraries
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows-static-md
