name: rust-action
description: Setup Rust Toolchain

inputs:
  target-toolchain:
    description: Target toolchain
    default: x86_64-unknown-linux-gnu
    required: false

runs:
  using: composite
  steps:
    - name: Cache Rust Toolchain
      uses: swatinem/rust-cache@v2
      with:
        prefix-key: "rust-${{ inputs.target-toolchain }}"
        cache-all-crates: true
        cache-targets: false

    - name: Get MSRV from Cargo.toml
      id: msrv
      shell: bash
      run: grep rust-version Cargo.toml | cut -d'"' -f2 | sed 's/^/version=/' >> $GITHUB_OUTPUT

    - name: Install Rust Toolchain
      shell: bash
      run: |
        rustup set auto-self-update disable
        rustup toolchain install ${{ steps.msrv.outputs.version }} --profile minimal --target ${{ inputs.target-toolchain }}
        rustup target add ${{ inputs.target-toolchain }}

    - name: Install Windows libraries
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        vcpkg install openssl:x64-windows-static-md 7zip

    - name: Install Cargo libraries
      shell: bash
      run: cargo install tsync --locked

    - name: Cargo libraries check
      shell: bash
      run: cargo check --all --bins --tests
