name: CI Test Build

on:
  push:
    branches-ignore: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    if: "!contains(github.event.commits[0].message, 'Merge branch')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          # - os: windows-latest
          #   target: x86_64-pc-windows-gnu
    name: CI build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run PNPM action
        uses: ./.github/pnpm-action
      - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        name: Build React SPA
        run: pnpm install && pnpm build

      - name: Setup Rust Toolchain
        uses: ./.github/rust-action
        with:
          target-toolchain: ${{ matrix.target }}

      - name: Compile Binaries
        run: cargo build --target ${{ matrix.target }} --release
