name: CI Test Build

# References:
# - https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
# - https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/
# - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

on:
  push:
    branches-ignore: [main,release]
    paths-ignore:
      - '**.md'
      - '.*ignore'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - 'Makefile.toml'
      - 'docs/'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    if: "!contains(github.event.commits[0].message, 'Merge branch')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          # - os: macos-12
          #   target: aarch64-apple-darwin
          # - os: macos-12
          #   target: x86_64-apple-darwin
          # - os: windows-2022
          #   target: x86_64-pc-windows-msvc
    name: CI build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/pnpm-action

      - name: Install npm dependencies
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build SPA frontend
        run: pnpm build

      - name: Setup Rust Toolchain
        uses: ./.github/rust-action
        with:
          target-toolchain: ${{ matrix.target }}

      - name: Compile ${{ matrix.target }}
        run: cargo build --target ${{ matrix.target }} --release --locked
