name: Release Stable

on:
  push:
    tags: ["v*.*.*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  discussions: write
  deployments: write
  packages: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.number }}

jobs:
  prepare-relase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update application version
        shell: bash
        run: |
          curl -fsSL https://github.com/gnprice/toml-cli/releases/download/v0.2.3/toml-0.2.3-x86_64-linux.tar.gz -o toml.tar.gz
          tar -xzvf toml.tar.gz && mv toml-0.2.3-x86_64-linux/toml /usr/local/bin/toml
          toml set Cargo.toml package.version ${{ github.ref }} > Cargo.toml.tmp
          cat Cargo.toml.tmp > Cargo.toml && rm Cargo.toml.tmp

      - name: Update repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "version bump to v${{ github.ref }} [skip actions]"
          commit_options: '--no-verify --signoff'
          # commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
          create_branch: false
