name: Release Stable

# References:
# - https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
# - https://ectobit.com/blog/speed-up-github-actions-rust-pipelines/

on:
  push:
    branches: ['release']
    paths: ['**/Cargo.toml', '.github/workflows/release-stable.yml']

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  discussions: write
  deployments: write
  packages: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.number }}
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  prepare-relase:
    runs-on: ubuntu-latest
    name: Prepare release
    steps:
      - uses: actions/checkout@v3
      - name: Setup release version
        working-directory: .
        shell: bash
        run: echo NEXT_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' Cargo.toml) >> $GITHUB_ENV
      - name: Validate release version
        shell: bash
        run: echo "Creating release v${{ env.NEXT_VERSION }}"
